name: 'Add a breakpoint to CI'
description: 'Pause, debug with SSH and resume GitHub Actions'
author: 'Namespace Labs'
branding:
  icon: 'pause-circle'
  color: 'blue'
inputs:
  endpoint:
    description: "The endpoint of a breakpoint rendezvous server."
    required: true
    default: "rendezvous.namespace.so:5000"
  duration:
    description: "The initial breakpoint duration."
    required: true
    default: "30m"
  authorized-users:
    description: "The comma-separated list of authorized GitHub users."
    required: false
  authorized-keys:
    description: "The comma-separated list of authorized SSH keys."
    required: false
  webhook-definition:
    description: "The path to a webhook definition file."
    required: false
  slack-announce-channel:
    description: "A slack channel where webhook sends notifications."
    required: false
runs:
  using: node16
  main: dist/main/index.js
