name: Lint and format check

on: [pull_request, push]

jobs:
  lint-format:
    permissions:
      contents: read
    runs-on: nscloud-ubuntu-22.04-amd64-2x8
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          # This should match the using value in `actions.yaml`
          node-version: 20

      - run: npm install
      - run: npm run lint
      - run: npm run format-check
